config/routes.rb
Rails.application.routes.draw do
  root to: 'moos#index'

  resources :moos
  resources :users 
  get '/moos/:id/reply' => 'moos#reply', as: :reply
  post '/moos/:id/like' => 'moos#like', as: :like
  get '/login' => 'users#login', as: :login
  post '/login' => 'users#start_session'
  get '/logout' => 'users#logout', as: :logout
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/moo.rb
# == Schema Information
#
# Table name: moos
#
#  id         :bigint(8)        not null, primary key
#  content    :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint(8)
#  moo_id     :bigint(8)
#  is_reply   :boolean
#

class Moo < ApplicationRecord
  has_and_belongs_to_many :likers, :join_table => :likes, class_name: 'User'
  belongs_to :owner, :class_name => 'User', :foreign_key => "user_id"
  belongs_to :reply_to, :class_name => 'Moo', :foreign_key => "moo_id", optional: true
  has_many :replies, :class_name => 'Moo', :foreign_key => "moo_id"
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint(8)        not null, primary key
#  username        :string
#  email           :string
#  password_digest :text
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  validates :username, :email, :uniqueness => true;
  has_secure_password
  has_and_belongs_to_many :likes, :join_table => :likes, class_name: "Moo"
  has_many :posts, dependent: :destroy, class_name: "Moo"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :check_login


  private
    def check_login
      @current_user = User.find_by(:id => session[:user_id]) if is_logged_in
    end

    def is_logged_in
      session[:user_id].present?
    end

    def redirect_if_not_signed_in
      redirect_to login_path unless is_logged_in
    end
end

app/controllers/moos_controller.rb
class MoosController < ApplicationController
  before_action :set_moo, only: [:show, :edit, :update, :destroy, :like]
  before_action :redirect_if_not_signed_in, only: [:new, :edit, :create, :like]
  # GET /moos
  # GET /moos.json
  def index
    @moos = Moo.all
  end

  # GET /moos/1
  # GET /moos/1.json
  def show
  end

  # GET /moos/new
  def new
    @moo = Moo.new
  end

  def reply
    @moo = Moo.new
    @moo.is_reply = true
    @moo.moo_id = params[:id]
    render action: :new
  end
  # GET /moos/1/edit
  def edit
  end

  # POST /moos/1/like
  def like
    if @moo.likers.include? @current_user
      @moo.likers.delete @current_user
    else
      @moo.likers << @current_user
    end
    redirect_to request.referrer
  end

  # POST /moos
  # POST /moos.json
  def create
    @moo = @current_user.posts.new(moo_params)
    respond_to do |format|
      if @moo.save
        format.html { redirect_to @moo, notice: 'Moo was successfully created.' }
        format.json { render :show, status: :created, location: @moo }
      else
        format.html { render :new }
        format.json { render json: @moo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /moos/1
  # PATCH/PUT /moos/1.json
  def update
    respond_to do |format|
      if @moo.update(moo_params)
        format.html { redirect_to @moo, notice: 'Moo was successfully updated.' }
        format.json { render :show, status: :ok, location: @moo }
      else
        format.html { render :edit }
        format.json { render json: @moo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /moos/1
  # DELETE /moos/1.json
  def destroy
    @moo.destroy
    respond_to do |format|
      format.html { redirect_to moos_url, notice: 'Moo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_moo
      @moo = Moo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def moo_params
      params.require(:moo).permit(:content, :moo_id, :is_reply)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def login
    # will render login form
  end

  def start_session
    user = User.find_by username: params[:username]
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      @msg = 'Incorrect username or password'
      render :login
    end
  end

  def logout
    session[:user_id] = nil
    redirect_to root_path
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/moos_helper.rb
module MoosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_moo.html.erb
<div class="moo">
  <div class="moo-header">
    <span class="username">
      @<%= m.owner.username %>
    </span>
    <span class="date">
      <%= m.created_at.strftime("%e-%b") %>
    </span>
  </div>
  <p class="content">
    <%= m.content %>
  </p>
  <div class="moo-options">
    <%= link_to "Reply (#{m.replies.count})", reply_path(m) %>
    <%= link_to "Like (#{m.likers.count})", like_path(m), method: :post %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MooApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
      <header>
        <div class="container flex-row">
          <p>Welcome to @Moo</p>
          <nav>
            <ul>
            <% if @current_user.present? %>
              <li>
                <%= link_to 'Moo!', new_moo_path %>
              </li><li>
                <%= link_to 'My Profile', user_path(@current_user.id) %>
              </li><li>
                <%= link_to 'Logout', logout_path %>
              </li>
            <% else %>
              <li>
                <%= link_to 'Moo!', new_moo_path %>
              </li><li>
                <%= link_to 'Login', login_path %>
              </li><li>
                <%= link_to 'Sign Up', new_user_path %>
              </li>
            <% end %>
            </ul>
          </nav>
        </div>
      </header>
    <div class="container">
      <main>
        <%= yield %>
      </main>
    </div>
  </body>
</html>

app/views/moos/_form.html.erb
<%= form_with(model: moo, local: true, class: 'moo-moo') do |form| %>
  <% if moo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(moo.errors.count, "error") %> prohibited this moo from being saved:</h2>

      <ul>
      <% moo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content, "Compose a new Moo" %>
    <%= form.text_area :content %>
  </div>

  <% if moo.is_reply %>
    <%= form.hidden_field :moo_id %>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/moos/edit.html.erb
<h1>Editing Moo</h1>

<%= render 'form', moo: @moo %>

<%= link_to 'Show', @moo %> |
<%= link_to 'Back', moos_path %>

app/views/moos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Moos</h1>

<% @moos.each do |moo| %>
  <%= render 'moo', m: moo %>
<% end %>

app/views/moos/new.html.erb
<%= render 'form', moo: @moo %>

<%= link_to 'Back', moos_path %>

app/views/moos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @moo.content %>
</p>

<%= link_to 'Like', like_path(@moo) %>
<%= link_to 'Edit', edit_moo_path(@moo) %> |
<%= link_to 'Back', moos_path %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>Password digest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= user.password_digest %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/login.html.erb
<h1>Login</h1>

<%= form_tag('/login', method: "post") do %>
  <% if @msg.present? %>
    <div id="error_explanation">
      <h2>Login failed</h2>

      <p><%= @msg %></p>
    </div>
  <% end %>

  <div class="field">
    <%= label_tag :username %>
    <%= text_field_tag :username %>
  </div>

  <div class="field">
    <%= label_tag :password %>
    <%= password_field_tag :password %>
  </div>

  <div class="actions">
    <%= submit_tag %>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<h1><%= @user.username %>'s Moos</h1>
<% @user.posts.each do |m| %>
  <%= render 'moo', m: m %>
<% end %>